### ISSUE TITLE
님 이제 폴더 만들어서 정리해봄이 어떰?

### ISSUE THREAD

**Issue by IngIeoAndSpare** [Roktar/codewars#1]
종류별로 정리하면 좀더 보기 편할것

**Comment by Roktar** [comment]
이제봤네 정리한다면 언어별/문제종류별 이런식으로?

**Comment by IngIeoAndSpare** [comment]
아마 코드워즈에 찾기나 알고리즘 태그 따라서 분류하면 되지 않을까

**Comment by Roktar** [comment]
흠 태그가 두 개 이상인 경우는 어떻게할 지 생각해봐야겠네
